<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/01/12 08:32:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrmdb',
  'username' => 'orangehrm_user',
  'password' => 'orangehrm_user_123',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
